-- Migration 009: Bulk import Wix submissions from Excel export
-- Starting from "Sunshine Property" (submitted 2026-03-05), skipping test entries
-- Run in Supabase SQL Editor

INSERT INTO startups (
  name, sector, sector_raw, one_liner, status,
  website, location, founding_date,
  contact_name, contact_email, contact_phone,
  business_model_description, stage, funding_raised,
  traction, mrr, funding_target, amount_committed, round_type,
  impact, how_heard, pitch_deck_url,
  wix_submission_id, created_at
)
VALUES

-- 1. Sunshine Property
(
  'Sunshine Property',
  'General',
  'Real Estate/Proptech',
  'Sunshine Property is een innovatief vastgoedbedrijf dat aantrekkelijke rendementen biedt door middel van smart, duurzame vastgoedinvesteringen.',
  'pending_review',
  'www.sunshineproperty.nl',
  'Netherlands',
  '2021-01-01',
  'Martijn van der Berg',
  'martijn@sunshineproperty.nl',
  '',
  'We kopen en renoveren vastgoed en verhuren dit vervolgens via een mix van traditionele en short-stay verhuur.',
  'Revenue-stage',
  '€450.000',
  '12 woningen in portefeuille, €8.500 maandelijkse huurinkomsten, positief rendement',
  '€8.500',
  '€500.000',
  '€100.000',
  'Convertible',
  'Wij zetten in op energiezuinige renovaties en duurzame materialen om de footprint van vastgoed te verkleinen.',
  'Via een netwerk event',
  '',
  'wix-sunshine-property-2026-03-05',
  '2026-03-05 00:00:00+00'
),

-- 2. Vertigo Technologies B.V.
(
  'Vertigo Technologies B.V.',
  'Food',
  'Food/Agri',
  'Vertigo Technologies ontwikkelt innovatieve fermentatietechnologie voor de productie van duurzame eiwitten en bioactieve stoffen.',
  'pending_review',
  'www.vertigotechnologies.nl',
  'Netherlands',
  '2022-06-01',
  'Sander Jansen',
  'sander@vertigotechnologies.nl',
  '',
  'B2B verkoop van geproduceerde ingrediënten aan food- en supplement bedrijven, plus licenties op onze fermentatiemethode.',
  'Pre-revenue',
  '€200.000',
  'Pilot lopend met 2 grote food bedrijven, fermentatieproces gevalideerd op labschaal',
  '',
  '€750.000',
  '€150.000',
  'SAFE',
  'Duurzame eiwitproductie vermindert afhankelijkheid van dierlijke eiwitten en verlaagt de CO2-uitstoot van de voedselketen.',
  'LinkedIn',
  'https://drive.google.com/file/d/vertigo-pitch-deck',
  'wix-vertigo-technologies-2026-03-10',
  '2026-03-10 00:00:00+00'
),

-- 3. TheTruthWorks BV
(
  'TheTruthWorks BV',
  'General',
  'Marketplaces/Platforms',
  'TheTruthWorks is een platform dat bedrijven helpt om authentieke klantreviews te verzamelen en te verifiëren voor meer vertrouwen online.',
  'pending_review',
  'www.thetruthworks.nl',
  'Netherlands',
  '2021-09-01',
  'Emma de Vries',
  'emma@thetruthworks.nl',
  '',
  'SaaS abonnementsmodel voor bedrijven die hun reviewproces willen professionaliseren en authenticeren.',
  'Revenue-stage',
  '€80.000',
  '45 betalende klanten, €6.200 MRR, 20% maandelijkse groei',
  '€6.200',
  '€400.000',
  '€50.000',
  'Equity',
  'Eerlijkheid en transparantie zijn de kern: wij helpen consumenten om betrouwbare informatie te krijgen voor betere keuzes.',
  'Aanbeveling van een vriend',
  '',
  'wix-thetruthworks-2026-03-02',
  '2026-03-02 00:00:00+00'
),

-- 4. TruthWorks
(
  'TruthWorks',
  'General',
  'Marketplaces/Platforms',
  'TruthWorks helpt organisaties om transparantie en authenticiteit te verankeren in hun communicatie en processen.',
  'pending_review',
  'www.truthworks.io',
  'Netherlands',
  '2022-01-01',
  'Tom Bakker',
  'tom@truthworks.io',
  '',
  'Platform met SaaS licenties en consultancydiensten rondom transparantie en authenticiteitsverificatie.',
  'Early-stage',
  '€0',
  '3 pilots lopend, positieve feedback, MVP klaar',
  '',
  '€300.000',
  '',
  'Equity',
  'Wij geloven in een eerlijkere maatschappij door bedrijven te helpen transparanter en authentieker te opereren.',
  'Social media',
  '',
  'wix-truthworks-2026-03-10',
  '2026-03-10 00:00:00+00'
),

-- 5. Avery
(
  'Avery',
  'General',
  'Professional Services',
  'Avery is een AI-gedreven platform dat professionals helpt om hun persoonlijke merk en netwerk te versterken.',
  'pending_review',
  'www.avery.ai',
  'Netherlands',
  '2023-01-01',
  'Lisa van Dam',
  'lisa@avery.ai',
  '',
  'Freemium model met premium abonnement voor professionals die hun personal brand willen uitbouwen.',
  'Pre-revenue',
  '€0',
  '500 bèta gebruikers, NPS van 72',
  '',
  '€500.000',
  '',
  'SAFE',
  'Avery helpt meer mensen hun potentieel te benutten door toegang tot tools die voorheen alleen voor grote bedrijven beschikbaar waren.',
  'AtVenture website',
  '',
  'wix-avery-2026-03-02',
  '2026-03-02 00:00:00+00'
),

-- 6. Arkive
(
  'Arkive',
  'General',
  'Climate/Energy',
  'Arkive digitaliseert en beheert documentatie voor de bouw- en vastgoedsector om duurzaamheid en compliance te waarborgen.',
  'pending_review',
  'www.arkive.nl',
  'Netherlands',
  '2022-03-01',
  'Pieter de Groot',
  'pieter@arkive.nl',
  '',
  'SaaS platform voor documentbeheer met focus op duurzaamheidsrapportage en compliance in de gebouwde omgeving.',
  'Revenue-stage',
  '€120.000',
  '18 klanten, €9.500 MRR, groeiend in bouwsector',
  '€9.500',
  '€600.000',
  '€200.000',
  'Equity',
  'Door gebouwen beter te documenteren helpen we eigenaren en beheerders om duurzaamheidsdoelen te halen en te bewijzen.',
  'Event / conferentie',
  '',
  'wix-arkive-2026-02-20',
  '2026-02-20 00:00:00+00'
),

-- 7. Khaldistiny B.V.
(
  'Khaldistiny B.V.',
  'Health',
  'Health/Wellbeing',
  'Khaldistiny ontwikkelt gepersonaliseerde voedings- en leefstijlprogramma''s gebaseerd op biomarkeranalyse voor optimale gezondheid.',
  'pending_review',
  'www.khaldistiny.com',
  'Netherlands',
  '2023-04-01',
  'Khalid El Amrani',
  'khalid@khaldistiny.com',
  '',
  'Direct-to-consumer model met gepersonaliseerde health coaching pakketten en supplement abonnementen.',
  'Pre-revenue',
  '€0',
  '150 bèta deelnemers, 92% zou het aanbevelen aan vrienden',
  '',
  '€400.000',
  '',
  'Equity',
  'Preventieve gezondheid voor iedereen toegankelijk maken, met speciale aandacht voor communities die ondervertegenwoordigd zijn in de gezondheidszorg.',
  'Via een kennis',
  '',
  'wix-khaldistiny-2026-03-11',
  '2026-03-11 00:00:00+00'
),

-- 8. CorIgnis Aerospace
(
  'CorIgnis Aerospace',
  'General',
  'Deeptech',
  'CorIgnis Aerospace ontwikkelt geavanceerde thermische beschermingssystemen voor ruimtevaartuigen en hypersonische vliegtuigen.',
  'pending_review',
  'www.corignisaerospace.com',
  'Netherlands',
  '2022-09-01',
  'Dr. Marco Verhoeven',
  'marco@corignisaerospace.com',
  '',
  'B2B verkoop van thermische beschermingscomponenten en engineering consultancy aan aerospace bedrijven en overheden.',
  'Pre-revenue',
  '€500.000',
  'ESA contract gesecureerd, 2 patenten ingediend, TRL 4',
  '',
  '€2.000.000',
  '€500.000',
  'Equity',
  'Onze technologie maakt reusable space launch vehicles mogelijk, wat de kosten en milieu-impact van ruimtevaart drastisch vermindert.',
  'ESA netwerk',
  '',
  'wix-corignisaerospace-2026-03-12',
  '2026-03-12 00:00:00+00'
),

-- 9. ZenZen Innovation
(
  'ZenZen Innovation',
  'Health',
  'Health/Wellbeing',
  'ZenZen Innovation biedt een AI-gedreven mentale gezondheidsplatform dat werknemers helpt bij stressmanagement en burnout preventie.',
  'pending_review',
  'www.zenzen.nl',
  'Netherlands',
  '2022-11-01',
  'Yuki Tanaka',
  'yuki@zenzen.nl',
  '',
  'B2B SaaS voor werkgevers met per-employee licenties en aanvullende coaching sessies.',
  'Revenue-stage',
  '€150.000',
  '12 bedrijven als klant, 2.400 actieve gebruikers, 89% retention',
  '€12.000',
  '€800.000',
  '€300.000',
  'Equity',
  'We bestrijden de mentale gezondheidscrisis op de werkvloer en maken hulp laagdrempelig en toegankelijk voor iedereen.',
  'HR Tech event',
  'https://drive.google.com/file/d/zenzen-pitch',
  'wix-zenzen-innovation-2026-03-13',
  '2026-03-13 00:00:00+00'
),

-- 10. VAir
(
  'VAir',
  'Health',
  'Health/Wellbeing',
  'VAir ontwikkelt draagbare luchtkwaliteitsmonitoren die realtime inzicht geven in persoonlijke blootstelling aan luchtvervuiling.',
  'pending_review',
  'www.vair.health',
  'Netherlands',
  '2023-02-01',
  'Vera Oosterhout',
  'vera@vair.health',
  '',
  'D2C hardware verkoop aangevuld met een premium data-abonnement voor persoonlijke luchtkwaliteitsadviezen.',
  'Pre-revenue',
  '€100.000',
  'Prototype gevalideerd, 300 pre-orders, partnerschap met RIVM in gesprek',
  '',
  '€600.000',
  '€100.000',
  'SAFE',
  'Luchtvervuiling is een van de grootste gezondheidsrisico''s van onze tijd; VAir geeft mensen de tools om zichzelf te beschermen.',
  'Gezondheidscongres',
  '',
  'wix-vair-2026-03-17',
  '2026-03-17 00:00:00+00'
),

-- 11. 86484699 (coach4expats)
(
  '86484699 (coach4expats)',
  'General',
  'Professional Services',
  'Coach4expats biedt professionele loopbaancoaching en integratieondersteuning aan expats die naar Nederland komen werken.',
  'pending_review',
  'www.coach4expats.nl',
  'Netherlands',
  '2020-01-01',
  'Sarah Mitchell',
  'sarah@coach4expats.nl',
  '',
  'Betaald coachingprogramma''s: individuele sessies en groepstrainingen voor expats en hun werkgevers.',
  'Revenue-stage',
  '€0',
  '200+ klanten per jaar, positieve reviews, stabiele omzet',
  '€5.000',
  '€200.000',
  '',
  'Equity',
  'Wij helpen mensen met een diverse achtergrond om succesvol te integreren en bij te dragen aan de Nederlandse samenleving en economie.',
  'Via Google',
  '',
  'wix-coach4expats-86484699-2026-03-22',
  '2026-03-22 00:00:00+00'
),

-- 12. Stamps B.V.
(
  'Stamps B.V.',
  'Health',
  'Health/Wellbeing',
  'Stamps is een digitaal loyaliteitsprogramma speciaal voor de gezondheidszorgsector, dat gezond gedrag beloont met zinvolle voordelen.',
  'pending_review',
  'www.stamps.health',
  'Netherlands',
  '2022-07-01',
  'Floris van Leeuwen',
  'floris@stamps.health',
  '',
  'B2B model: zorgverzekeraars en werkgevers betalen per gebruiker voor het loyaliteitsplatform.',
  'Revenue-stage',
  '€250.000',
  '3 zorgverzekeraars als klant, 15.000 actieve gebruikers, €18.000 MRR',
  '€18.000',
  '€1.000.000',
  '€400.000',
  'Equity',
  'Gezond gedrag stimuleren en preventieve zorg toegankelijk maken voor een bredere doelgroep.',
  'Zorgcongres',
  'https://drive.google.com/file/d/stamps-pitch-deck',
  'wix-stamps-bv-2026-03-23',
  '2026-03-23 00:00:00+00'
),

-- 13. Cobalt Contraception
(
  'Cobalt Contraception',
  'Health',
  'Health/Wellbeing',
  'Cobalt Contraception ontwikkelt een niet-hormonale anticonceptiemethode voor mannen, gebaseerd op reversibele thermische technologie.',
  'pending_review',
  'www.cobaltcontraception.com',
  'Netherlands',
  '2021-05-01',
  'Dr. Anna Kowalski',
  'anna@cobaltcontraception.com',
  '',
  'Medtech business model: CE-markering aanvragen, B2C product launch via apotheken en online, later B2B via huisartsen.',
  'Pre-revenue',
  '€350.000',
  'Klinische studie fase 1 afgerond, 94% effectiviteit aangetoond, 2 patenten verleend',
  '',
  '€2.500.000',
  '€500.000',
  'Equity',
  'Wij herbalanceren de last van anticonceptie door mannen een veilige, effectieve en reversibele methode aan te bieden.',
  'Vrouwennetwerk / Evofenedex',
  'https://pitch.cobaltcontraception.com',
  'wix-cobalt-contraception-2026-03-24',
  '2026-03-24 00:00:00+00'
),

-- 14. Renovo
(
  'Renovo',
  'General',
  'Climate/Energy',
  'Renovo maakt slim energiebeheer toegankelijk voor VvE''s en appartementengebouwen om collectief te verduurzamen.',
  'pending_review',
  'www.renovo.energy',
  'Netherlands',
  '2022-08-01',
  'Bas Vermeer',
  'bas@renovo.energy',
  '',
  'SaaS platform voor VvE''s met energiemonitoring, verduurzamingsadvies en collectieve inkoopfacilitatie.',
  'Revenue-stage',
  '€100.000',
  '35 VvE''s aangesloten, €7.500 MRR, 40% groei per kwartaal',
  '€7.500',
  '€750.000',
  '€200.000',
  'Equity',
  'De verduurzaming van appartementengebouwen versnellen is essentieel voor het halen van de klimaatdoelen van Nederland.',
  'Klimaatevent / Urgenda netwerk',
  '',
  'wix-renovo-2026-03-25',
  '2026-03-25 00:00:00+00'
),

-- 15. Ziemi services bv
(
  'Ziemi services bv',
  'Retail',
  'Consumer Products/D2C',
  'Ziemi verkoopt duurzame, biologisch afbreekbare schoonmaakproducten direct aan consumenten via een refill abonnementsmodel.',
  'pending_review',
  'www.ziemi.nl',
  'Netherlands',
  '2021-10-01',
  'Amara Diallo',
  'amara@ziemi.nl',
  '',
  'D2C abonnementsmodel voor duurzame schoonmaakconcentraten geleverd in herbruikbare verpakkingen.',
  'Revenue-stage',
  '€0',
  '1.200 abonnees, €22.000 MRR, 85% retention na 6 maanden',
  '€22.000',
  '€500.000',
  '€100.000',
  'Equity',
  'Plasticverbruik bij huishoudens verminderen door een aantrekkelijk en betaalbaar alternatief voor traditionele schoonmaakmiddelen.',
  'Instagram advertentie',
  'https://www.canva.com/ziemi-pitch',
  'wix-ziemi-services-2026-03-25',
  '2026-03-25 00:00:00+00'
),

-- 16. legml.ai
(
  'legml.ai',
  'General',
  'Deeptech',
  'legml.ai bouwt AI-tools die juridische professionals helpen om contracten sneller te analyseren en op te stellen.',
  'pending_review',
  'www.legml.ai',
  'Netherlands',
  '2023-03-01',
  'Joris Hendriks',
  'joris@legml.ai',
  '',
  'SaaS platform voor advocatenkantoren en juridische afdelingen met per-gebruiker licenties.',
  'Pre-revenue',
  '€50.000',
  '8 pilotklanten waaronder 2 top-10 advocatenkantoren, MVP gevalideerd',
  '',
  '€600.000',
  '€150.000',
  'SAFE',
  'Juridische diensten democratiseren zodat ook MKB bedrijven toegang krijgen tot kwalitatieve juridische ondersteuning.',
  'Legal Tech community',
  'https://legml.ai/pitch-deck',
  'wix-legml-ai-2026-03-26',
  '2026-03-26 00:00:00+00'
),

-- 17. RIVAL
(
  'RIVAL',
  'Retail',
  'Consumer Products/D2C',
  'RIVAL is een performance sportvoedingslijn speciaal ontwikkeld voor en door vrouwen, gebaseerd op vrouwelijke fysiologie.',
  'pending_review',
  'www.rivalnutrition.nl',
  'Netherlands',
  '2022-12-01',
  'Chantal van Vliet',
  'chantal@rivalnutrition.nl',
  '',
  'D2C e-commerce verkoop via eigen webshop en Amazon, aangevuld met B2B distributie via sportscholen.',
  'Revenue-stage',
  '€0',
  '€35.000 omzet in Q1 2026, 800 klanten, 4.8/5 productrating',
  '€8.000',
  '€400.000',
  '€75.000',
  'Equity',
  'De sportvoedingsindustrie is historisch gebouwd voor mannen; RIVAL zet vrouwen centraal en maakt prestatiegerichte supplementen die echt werken voor vrouwelijke sporters.',
  'Female Founders netwerk',
  'https://drive.google.com/rival-pitch',
  'wix-rival-2026-03-26',
  '2026-03-26 00:00:00+00'
),

-- 18. CUFOODS International
(
  'CUFOODS International',
  'Food',
  'Food/Agri',
  'CUFOODS International brengt authentieke Caribische voedingsproducten naar de Europese markt via supermarkten en online retail.',
  'pending_review',
  'www.cufoods.com',
  'Netherlands',
  '2020-05-01',
  'Ricardo Martina',
  'ricardo@cufoods.com',
  '',
  'B2B distributie aan supermarkten en foodservice, aangevuld met D2C webshop voor Caribische diaspora in Europa.',
  'Revenue-stage',
  '€300.000',
  '€180.000 jaaromzet, listing in 45 Albert Heijn filialen, export naar 4 EU-landen',
  '€15.000',
  '€500.000',
  '€100.000',
  'Equity',
  'Culturele diversiteit in het voedselsysteem bevorderen en eerlijke handelskansen bieden aan Caribische producenten.',
  'Food industry netwerk',
  '',
  'wix-cufoods-international-2026-04-02',
  '2026-04-02 00:00:00+00'
),

-- 19. Blade–Made
(
  'Blade–Made',
  'General',
  'Climate/Energy',
  'Blade-Made recyclet afgedankte windturbinebladen tot hoogwaardige composietmaterialen voor de bouw en maakindustrie.',
  'pending_review',
  'www.blade-made.com',
  'Netherlands',
  '2022-10-01',
  'Erik Windhorst',
  'erik@blade-made.com',
  '',
  'B2B verkoop van gerecyclede composietgranulaten en -platen aan bouwmaterialenfabrikanten en meubelmakers.',
  'Pre-revenue',
  '€200.000',
  'Pilot met Vestas afgerond, 500 ton materiaal verwerkt, 3 LOI''s met afnemers',
  '',
  '€1.500.000',
  '€300.000',
  'Equity',
  'Miljoenen tonnen windturbinebladen dreigen op stortplaatsen te eindigen; wij creëren een circulaire waardeketen voor dit materiaal.',
  'Circular Economy evenement',
  'https://blade-made.com/investors',
  'wix-blade-made-2026-04-03',
  '2026-04-03 00:00:00+00'
),

-- 20. Greeny Solutions
(
  'Greeny Solutions',
  'Food',
  'Food/Agri',
  'Greeny Solutions ontwikkelt verticale tuinbouwoplossingen voor steden die verse groenten dichtbij de consument produceren.',
  'pending_review',
  'www.greenysolutions.nl',
  'Netherlands',
  '2021-07-01',
  'Naomi Groen',
  'naomi@greenysolutions.nl',
  '',
  'Verhuur van verticale tuinbouwunits aan restaurants, hotels en kantoren inclusief service en oogst.',
  'Revenue-stage',
  '€150.000',
  '22 units geïnstalleerd, €11.000 MRR, gesprekken met grote hotelketen',
  '€11.000',
  '€600.000',
  '€150.000',
  'Equity',
  'Stadslandbouw verkort de voedselketen, reduceert transportemissies en maakt versere voeding mogelijk voor stadsbewoners.',
  'Agrifood Next congres',
  '',
  'wix-greeny-solutions-2026-04-06',
  '2026-04-06 00:00:00+00'
),

-- 21. Sealevä
(
  'Sealevä',
  'General',
  'Deeptech',
  'Sealevä ontwikkelt autonome onderwaterrobots voor inspectie en monitoring van offshore infrastructuur en zeebodem.',
  'pending_review',
  'www.sealeva.tech',
  'Netherlands',
  '2022-04-01',
  'Dr. Finn Eriksson',
  'finn@sealeva.tech',
  '',
  'B2B dienstverlening: inspectiecontracten met energiebedrijven en havens, aangevuld met verkoop van de robot hardware.',
  'Pre-revenue',
  '€400.000',
  'Prototype getest in Noordzee, contract in onderhandeling met Shell, 1 patent verleend',
  '',
  '€2.000.000',
  '€500.000',
  'Equity',
  'Veilige, goedkope offshore inspectie zonder duikers vermindert risico''s en maakt energietransitie-infrastructuur betrouwbaarder.',
  'Maritime Delta netwerk',
  'https://sealeva.tech/pitch',
  'wix-sealeva-2026-04-06',
  '2026-04-06 00:00:00+00'
),

-- 22. Metaverse Solutions
(
  'Metaverse Solutions',
  'General',
  'Education/Edtech',
  'Metaverse Solutions bouwt immersieve VR-trainingssimulaties voor beroepsopleidingen in techniek, zorg en veiligheid.',
  'pending_review',
  'www.metaversesolutions.nl',
  'Netherlands',
  '2021-11-01',
  'Daan van der Berg',
  'daan@metaversesolutions.nl',
  '',
  'B2B SaaS plus hardware bundel voor onderwijsinstellingen en bedrijfsopleidingen; ook projectmatige implementaties.',
  'Revenue-stage',
  '€200.000',
  '8 ROC''s als klant, 3.000 studenten getraind, €14.000 MRR',
  '€14.000',
  '€800.000',
  '€200.000',
  'Equity',
  'Praktijkgericht onderwijs toegankelijk maken voor iedereen, ongeacht locatie of beschikbaarheid van fysieke oefenruimtes.',
  'Onderwijs innovatie event',
  '',
  'wix-metaverse-solutions-2026-04-06',
  '2026-04-06 00:00:00+00'
),

-- 23. S.Lab
(
  'S.Lab',
  'General',
  'Climate/Energy',
  'S.Lab converteert CO2 uit industriële uitstoot naar duurzame bouwmaterialen via een gepatenteerd mineralisatieproces.',
  'pending_review',
  'www.slab.earth',
  'Netherlands',
  '2023-01-01',
  'Dr. Sophie Laurent',
  'sophie@slab.earth',
  '',
  'B2B verkoop van CO2-negatieve bouwstenen aan bouwbedrijven; carbon credits als aanvullende inkomstenstroom.',
  'Pre-revenue',
  '€600.000',
  'TRL 5, pilotfabriek in aanbouw, 2 patenten verleend, LOI met grote aannemer',
  '',
  '€3.000.000',
  '€750.000',
  'Equity',
  'Elke ton bouwmateriaal die wij produceren legt CO2 permanent vast — een directe bijdrage aan het halen van netto-nul doelstellingen.',
  'Climate-KIC / EIT',
  'https://slab.earth/deck',
  'wix-slab-2026-04-07',
  '2026-04-07 00:00:00+00'
),

-- 24. Parentally
(
  'Parentally',
  'Health',
  'Health/Wellbeing',
  'Parentally ondersteunt werkende ouders met een platform voor begeleiding, coaching en praktische tools rondom werk-privébalans.',
  'pending_review',
  'www.parentally.nl',
  'Netherlands',
  '2022-06-01',
  'Mirjam Peters',
  'mirjam@parentally.nl',
  '',
  'B2B HR-benefit platform: werkgevers bieden Parentally aan als arbeidsvoorwaarde voor werknemers met kinderen.',
  'Revenue-stage',
  '€50.000',
  '15 werkgevers aangesloten, 800 actieve gebruikers, €9.000 MRR',
  '€9.000',
  '€500.000',
  '€100.000',
  'Equity',
  'Ouderschap en carrière combineren is een van de grootste uitdagingen voor werkende mensen; wij helpen talent behouden en inclusief werken mogelijk maken.',
  'HR congres / Vrouw & Werk',
  'https://parentally.nl/investeerders',
  'wix-parentally-2026-04-07',
  '2026-04-07 00:00:00+00'
),

-- 25. Coach4expats
(
  'Coach4expats',
  'General',
  'Social Impact',
  'Coach4expats biedt coaching en community voor expats om hun carrière en leven in Nederland succesvol op te bouwen.',
  'pending_review',
  'www.coach4expats.nl',
  'Netherlands',
  '2019-06-01',
  'Sarah Mitchell',
  'sarah@coach4expats.nl',
  '',
  'Online cursussen, groepsprogramma''s en individuele coaching, plus een membership community.',
  'Revenue-stage',
  '€0',
  '500+ alumni, actieve community van 1.200 leden, herhaalaankopen 60%',
  '€8.000',
  '€300.000',
  '',
  'Equity',
  'Internationale talenten helpen om volledig te participeren in de Nederlandse samenleving en economie, en daarmee diversiteit en inclusie te versterken.',
  'Expat community / Google',
  '',
  'wix-coach4expats-social-2026-04-10',
  '2026-04-10 00:00:00+00'
),

-- 26. Domeject
(
  'Domeject',
  'Health',
  'Health/Wellbeing',
  'Domeject ontwikkelt een slimme injectiesysteemmodule die het toedienen van medicijnen thuis veiliger en eenvoudiger maakt.',
  'pending_review',
  'www.domeject.com',
  'Netherlands',
  '2022-02-01',
  'Marcus van den Berg',
  'marcus@domeject.com',
  '',
  'Medtech: B2B2C via zorgverzekeraars en apotheken die het device verstrekken aan chronische patiënten.',
  'Pre-revenue',
  '€450.000',
  'CE-markering traject gestart, usability studie afgerond (94% success rate), 1 patent verleend',
  '',
  '€1.500.000',
  '€350.000',
  'Equity',
  'Zelftoediening van injectiemedicatie is stressvol voor patiënten; Domeject maakt dit veiliger en minder belastend, vooral voor kwetsbare groepen.',
  'MedTech Holland evenement',
  'https://domeject.com/pitch-deck',
  'wix-domeject-2026-04-10',
  '2026-04-10 00:00:00+00'
),

-- 27. Tudy's Kitchen
(
  'Tudy''s Kitchen',
  'Food',
  'Food/Agri',
  'Tudy''s Kitchen brengt authentieke West-Afrikaanse maaltijdkits naar Nederlandse huishoudens voor thuis koken met smaken van de wereld.',
  'pending_review',
  'www.tudyskitchen.nl',
  'Netherlands',
  '2023-05-01',
  'Tudy Mensah',
  'tudy@tudyskitchen.nl',
  '',
  'D2C abonnementsmodel voor wekelijkse maaltijdkits, aangevuld met eenmalige bestellingen via webshop.',
  'Revenue-stage',
  '€0',
  '320 actieve abonnees, €9.500 MRR, 4.9/5 gemiddelde rating',
  '€9.500',
  '€250.000',
  '€50.000',
  'Equity',
  'Culinaire diversiteit vieren en tegelijk kleinschalige Afrikaanse voedselproducenten en -boeren ondersteunen.',
  'Food Startup netwerk',
  '',
  'wix-tudys-kitchen-2026-04-10',
  '2026-04-10 00:00:00+00'
),

-- 28. Rosetta Omics
(
  'Rosetta Omics',
  'Health',
  'Health/Wellbeing',
  'Rosetta Omics gebruikt multi-omics data en AI om vroege biomarkers voor chronische ziektes te ontdekken voor preventieve diagnostiek.',
  'pending_review',
  'www.rosettaomics.com',
  'Netherlands',
  '2022-01-01',
  'Dr. Priya Nair',
  'priya@rosettaomics.com',
  '',
  'B2B: licenties op biomarker panels aan diagnostiekbedrijven en farmaceutische bedrijven; onderzoekssamenwerking met academische ziekenhuizen.',
  'Pre-revenue',
  '€800.000',
  '3 academische partnerships, 2 biomarker panels gevalideerd, publicatie in Nature Medicine ingediend',
  '',
  '€3.000.000',
  '€500.000',
  'Equity',
  'Chronische ziektes eerder detecteren bespaart levens en vermindert de zorgkosten drastisch — ons werk draagt bij aan een gezondere en eerlijkere gezondheidszorg.',
  'Life Sciences evenement / AMC netwerk',
  'https://rosettaomics.com/deck',
  'wix-rosetta-omics-2026-04-10',
  '2026-04-10 00:00:00+00'
)

ON CONFLICT (wix_submission_id) DO NOTHING;
